AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Library API - Lambda Backend

Parameters:
  SpreadsheetId:
    Type: String
    Description: Google Spreadsheet ID
  GcpProjectNumber:
    Type: String
    Description: GCP Project Number for Workload Identity Federation
    Default: ''
  GcpWifPoolId:
    Type: String
    Description: Workload Identity Pool ID
    Default: ''
  GcpWifProviderId:
    Type: String
    Description: Workload Identity Provider ID
    Default: ''
  GcpServiceAccountEmail:
    Type: String
    Description: GCP Service Account email for Sheets API access
    Default: ''
  AllowedDomains:
    Type: String
    Description: Comma-separated list of allowed email domains
    Default: ''
  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID for ID Token verification
  AllowedOrigin:
    Type: String
    Description: Allowed CORS origin (e.g. https://your-domain.com)

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs24.x

Resources:
  LibraryApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/index.handler
      CodeUri: .
      AutoPublishAlias: prd
      FunctionUrlConfig:
        AuthType: AWS_IAM
      Environment:
        Variables:
          SPREADSHEET_ID: !Ref SpreadsheetId
          GCP_PROJECT_NUMBER: !Ref GcpProjectNumber
          GCP_WIF_POOL_ID: !Ref GcpWifPoolId
          GCP_WIF_PROVIDER_ID: !Ref GcpWifProviderId
          GCP_SERVICE_ACCOUNT_EMAIL: !Ref GcpServiceAccountEmail
          ALLOWED_DOMAINS: !Ref AllowedDomains
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          ALLOWED_ORIGIN: !Ref AllowedOrigin

Outputs:
  FunctionUrl:
    Description: Lambda Function URL (prd alias)
    Value: !GetAtt LibraryApiFunctionUrl.FunctionUrl
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt LibraryApiFunction.Arn
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref LibraryApiFunction
